# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjcFrame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcFrame
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.1.0' # HUD
  pod 'IQKeyboardManager' # 键盘
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry' # 布局
  pod 'SDCycleScrollView','>= 1.80' # 轮播图
  pod 'XHLaunchAd'  # 启动页广告图

end
