# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjcFrame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcFrame
  pod 'AFNetworking'
  pod 'MBProgressHUD' # HUD
  pod 'SVProgressHUD' # HUD
  pod 'IQKeyboardManager' # 键盘
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry' # 布局
  pod 'SDCycleScrollView' # 轮播图
  pod 'XHLaunchAd'  # 启动页广告图
  pod 'JPush'  # 极光推送

end
