# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'QShortVideo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QShortVideo
  pod 'PLShortVideoKit' #七牛云短视频
  pod 'PLPlayerKit' #视频播放
  pod 'Alamofire', '~> 5.0' #网络请求
  pod 'MBProgressHUD', '~> 1.2.0' #蒙版
  pod 'SVProgressHUD'
  pod 'SwiftyJSON', '~> 4.0'  #字典转模型
  pod 'SnapKit', '~> 5.0.0' #布局
  
  target 'QShortVideoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QShortVideoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
